name: aca-keda-demo
metadata:
  template: aca-keda-demo@0.0.1
services:
  api:
    project: ./src/Bugay.Api.Example
    language: dotnet
    host: containerapp
    docker:
      image: aca-keda-demo/api-dev
      path: ./Dockerfile
      context: .
      remoteBuild: true
infra:
  provider: terraform
